### ISSUE TITLE
Unable to create separate tabs for app using ggplotly and R

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_R-dash#10]
Hi Team, 

I have tried multiple times but was unable to create separate tabs in R/ggplotly as we did using dash/altair. 
Please see if you can find something otherwise we might need to check with Firas or/and come with alternative design. 

Thanks!

**Comment by YueJiangMDSV** [comment]
We can check with Firas tomorrow. If we can create separate tabs, maybe we can just put everything in one tab?

**Comment by arunmarria** [comment]
Yeah that is what I was thinking. There are options to embed multiple charts in one page. Lets see if Firas has any inputs on this! but definitely he was right as there is limited functionality of dash with R as compared to python!

**Comment by YueJiangMDSV** [comment]
Yep, let's see what he says. Thanks a lot for working on the app ahead!

BTW, he showed an interactive table today in app4.r. Looks interesting. Maybe we can implement that?

**Comment by arunmarria** [comment]
Thanks @rita-ni 

#14
