### ISSUE TITLE
Status update on R dashboard

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_R-dash#11]
- I have updated first tab's charts with interaction in R/gglotly (except that slider bar as i am not sure if we can do that in R) otherwise we will need to create a simple slider for time range. 
- I should be able to finish converting second chart before tomorrow's lab. 

Will create pull request before lab tomorrow!
cc @YueJiangMDSV @rita-ni

**Comment by arunmarria** [comment]
All charts interactivity done and completed. Following tasks need to be done 
- Better styling @rita-ni , @YueJiangMDSV  can you please check on that?

**Comment by rita-ni** [comment]
> All charts interactivity done and completed. Following tasks need to be done
> 
> * Better styling @rita-ni , @YueJiangMDSV  can you please check on that?

Will do, I will also check on the bar chart callback

**Comment by YueJiangMDSV** [comment]
Hi team @arunmarria @rita-ni ,

If you have time, can you please take a look at the x-axis and y-axis labels of the second chart on tab2? They seem to be chopped out on my laptop. I tried to change the margin, but it does not work. Not sure how it looks in different laptops. 

Also, if you have time, can you please double check if there are any grammar mistakes or typos?
 
Thanks!

**Comment by arunmarria** [comment]
Sure. Will check now; Thanks Alex!

**Comment by YueJiangMDSV** [comment]
Great job everyone!

**Comment by rita-ni** [comment]
Thanks everyone, I am closing this issue as the tasks discussed here are all solved in our app
