### ISSUE TITLE
Status update on app deployment

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_R-dash#19]

**Comment by YueJiangMDSV** [comment]
I just got home. I'll work on it tonight or tomorrow

**Comment by YueJiangMDSV** [comment]
Hi team,

Good news: I can deploy the app! See it here https://test-dsci532-alex.herokuapp.com/

I used the old version. It requires some changes in the library and theme. 
We also need to change the data path to url. 
Another thing is we need to get rid of   
    panel_border() +
    background_grid()
Good thing is these changes did not affect the app much.

I'll try the latest version of the app tomorrow. If it works, I'll create a pull request for all the required files and the updated app.

**Comment by YueJiangMDSV** [comment]
I tried this morning, and the latest version can be deployed as well. I'll update the files later.

**Comment by rita-ni** [comment]
> I tried this morning, and the latest version can be deployed as well. I'll update the files later.

Thank you Alex, this is great! If the app can deploy without any issues then we can focus on polishing our plots! I believe we already have most things worked out. Great work!

**Comment by arunmarria** [comment]
Thanks closing this as we can deploy app!
