### ISSUE TITLE
Need to work on /edit  app sketch and description milestone 3

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_R-dash#2]
Hi Team,

Milestone 1 grades are released. We got maximum marks in all sections of milestone 1 including sketch,proposal etc, Good job!

But got 82% in code of conduct and team contract section. So we will probably need to update that for milestone 3. As discussed earlier in our meeting, assigning this to @YueJiangMDSV, can you please check on this?

Thanks!

**cc** @rita-ni

**Comment by YueJiangMDSV** [comment]
Actually, we got 95% for Team Contract and Code of Conduct....
It is Description of your app & sketch that we got 82%...
At least this is what I saw on my grade report...
Anyway, I can definitely go over the team contract and code of conduct, and update them if necessary.

**Comment by arunmarria** [comment]
You're right,  I just rechecked the grade report. Sorry my bad!

EDIT - I updated issue accordingly. 

And Lets talk to TA or Firas tomorrow for detailed feedback, so we can do this better for milestone 3.

**Comment by YueJiangMDSV** [comment]
No worries. I just created a new pull request including the new sketch. We can show them the new one tomorrow, and see how we can improve it.

**Comment by arunmarria** [comment]
Completed by @YueJiangMDSV
