### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by YueJiangMDSV** [UBC-MDS/DSCI-532_group-211_R-dash#21]
Hi team,
For the latest version, I edited the font size and color. I also updated the data table in tab 1 to make it interactive. You can check it here: https://r-repo-new-test.herokuapp.com/

I still do not know how to deploy the app without the button. I asked Firas on Slack, and let's see what he says. 

Another thing is when I deployed the app, there is this warning message: 

Warning: Your slug size (354 MB) exceeds our soft limit (300 MB) which may affect boot time.

Not sure how this affects our app. Maybe we can ask Firas about that as well.

**Comment by YueJiangMDSV** [comment]
Hi team, 

I checked with Firas:

1. We need the button to deploy.
2. The warning does not matter. The hard limit is 500 MB. So we should be fine.

**Comment by arunmarria** [comment]
Thanks for checking @YueJiangMDSV ,  We don't have any deployment issues then. And we can then start working on any changes (if we want) to the app. 

And documentation part. For documentation we only need reflections right?

cc @rita-ni

**Comment by YueJiangMDSV** [comment]
Yeah, I just read the Milestone 4 again. We need to write the reflections. And we might need to slightly change the README file to update with the app functions.

**Comment by YueJiangMDSV** [comment]
Hi team,

The latest version of app can be found here: https://r-repo-new-test.herokuapp.com/

If you have time, please try to deploy the app as well. Just want to make sure the app works in different laptops/environments. Thanks!

**Comment by arunmarria** [comment]
Thanks Alex and Rita. Good job deploying app! #27
