### ISSUE TITLE
Plots for dashR app

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI-532_group-211_R-dash#8]
Hi @YueJiangMDSV , 

As discussed, can you please share the ggplot code for static plots you created for milestone 3. We can then start working on our R app. 

Thanks!

cc @rita-ni

**Comment by YueJiangMDSV** [comment]
Sure. I'll upload shortly and create a pull request.

**Comment by arunmarria** [comment]
#9
